import Discount from "./_components/modules/discount";
import Footer from "./_components/modules/footer";
import Scroller from "./_components/modules/scroller";
import Navbar from "./_components/template/navbar";
import "./globals.css";
import ThemeToggle from "./_components/modules/themeToggle";
import { Toaster } from "react-hot-toast";
import BreadCrumb from "./_components/modules/breadCrumb";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "MAGHALEH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="root" suppressHydrationWarning>
      <body className="bg-first dark:bg-[#1e293b]">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeToggle />
          <Navbar />
          <Discount />
          <div className="w-full px-6 sm:px-[5rem] md:px-[10rem] xl:px-[15rem] sm:pt-16 md:pt-16 lgg:pt-20">
            <BreadCrumb />

            {children}
            <Scroller />
          </div>
          <Footer />
          <Toaster position="bottom-left" reverseOrder={false} />
        </ThemeProvider>
      </body>
    </html>
  );
}
