import ContextProvider from "@/utils/context";
import Discount from "./components/modules/discount";
import Footer from "./components/modules/footer";
import Hr from "./components/modules/hr";
import Scroller from "./components/modules/scroller";
import Navbar from "./components/template/navbar";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

export const metadata = {
  title: "MAGHALEH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-first">
        <ContextProvider>
          <NextUIProvider>
            <Navbar />
            <Hr />
            <div className="w-full px-6 sm:px-[5rem] md:px-[10rem] xl:px-[15rem]">
              <Discount />
              {children}
              <Scroller />
            </div>
            <Footer />
          </NextUIProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
